### ISSUE TITLE
Alternate System Support (Integrant/mount/etc)

### ISSUE THREAD

**Issue by wmatson** [amperity/greenlight#35]
### Request
Please provide support to use system management libraries other than `com.stuartsierra/component`, for example [integrant](https://github.com/weavejester/integrant)

### Justification
I understand I could use a bridge of sorts to handle starting/stopping an `integrant` system using `component`, but it'd be nice to choose my own way of managing stateful portions of integration tests. It'd probably also be for the best if the core `greenlight` project didn't depend on a particular version of `component` anyway.

----
### Suggested design:

One potential pattern I've seen for handling this is to provide a multimethod/protocol hook for the relevant operations and a library for each "popular/supported" framework that includes the relevant polymorphic implementations of the hook for said framework.

**Comment by wmatson** [comment]
I'd be happy to work on this/submit a PR if amperity agrees with the idea

**Comment by jstokes** [comment]
Thanks @wmatson. I'm in favor of the idea, and happy to provide support. We could split off the `com.stuartsierra/component` implementation into a separate Amperity library if that's the direction you're thinking of heading.

**Comment by wmatson** [comment]
Any opposition to upgrading to clojure 1.10 for `:extend-via-metadata` on the protocol?

**Comment by jstokes** [comment]
Released in 0.1.7
