### ISSUE TITLE
Repo defaults to development branch

### ISSUE THREAD

**Issue by djtango** [amperity/greenlight#40]
Noob fail on my part but the default branch on Github is development which means that the README relates to unreleased features by default which is misleading (was trying to use the `runner/ManagedSystem` protocol only to realise it's not been merged into master yet

**Comment by jstokes** [comment]
Apologies, I should have released that sooner (it's now in 0.1.7). We've set `develop` as the default branch so pull requests are automatically opened against that branch instead of `master`.

**Comment by djtango** [comment]
> We've set develop as the default branch so pull requests are automatically opened against that branch instead of master.

Fair enough - thanks for shipping 0.1.7
